# This workflow will build and push a new container image to GitHub Container Registry
# when there is a push to the "main" branch.
#
# This workflow avoids AWS ECR permissions issues by using GitHub Container Registry instead.

name: Build and Push Credit Scoring Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd frontend && npm install

      - name: Run smart contract tests
        run: npm run test

      - name: Run frontend tests
        run: |
          cd frontend
          npm run test -- --coverage --watchAll=false

  build-and-push:
    name: Build and Push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          # Build Docker image
          docker build -t ghcr.io/${{ github.repository }}/credit-scoring-dashboard:latest .
          docker build -t ghcr.io/${{ github.repository }}/credit-scoring-dashboard:${{ github.sha }} .
          
          # Push to GitHub Container Registry
          docker push ghcr.io/${{ github.repository }}/credit-scoring-dashboard:latest
          docker push ghcr.io/${{ github.repository }}/credit-scoring-dashboard:${{ github.sha }}

      - name: Verify image push
        run: |
          echo "✅ Docker image pushed successfully!"
          echo "📦 Image: ghcr.io/${{ github.repository }}/credit-scoring-dashboard:latest"
          echo "📦 Image: ghcr.io/${{ github.repository }}/credit-scoring-dashboard:${{ github.sha }}"
          echo "🔗 View at: https://github.com/${{ github.repository }}/pkgs/container/credit-scoring-dashboard"
